<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PRL" name="Test" tests="3" failures="1" timestamp="31 Jan 2017 10:23:02 GMT" time="19.975" errors="0">
  <testcase name="TestCase 1" time="3.847" classname="com.prl.soapuitest.TestCreator"/>
  <testcase name="TestCase2" time="0.003" classname="com.prl.soapuitest.TestCreator"/>
  <testcase name="GroovyTest1" time="16.046" classname="com.prl.soapuitest.TestCreator">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
	at com.prl.soapuitest.TestCreator.Test1(TestCreator.java:38)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- GroovyTest1 -->
</testsuite> <!-- Test -->
